// Generated by BUCKLESCRIPT VERSION 4.0.7, PLEASE EDIT WITH CARE
'use strict';


var me = /* record */[
  /* age */23,
  /* name */"Vasya",
  /* occupation */"Student"
];

exports.me = me;
/* No side effect */
