// Generated by BUCKLESCRIPT VERSION 4.0.7, PLEASE EDIT WITH CARE
'use strict';


function getAge(entity) {
  return entity[/* age */0];
}

var me = /* record */[
  /* age */33,
  /* name */"Igor"
];

var monster = /* record */[
  /* age */999,
  /* hasTentacles */true
];

var monsterAge = 33;

exports.getAge = getAge;
exports.me = me;
exports.monster = monster;
exports.monsterAge = monsterAge;
/* No side effect */
