// Generated by BUCKLESCRIPT VERSION 4.0.7, PLEASE EDIT WITH CARE
'use strict';


var igor = /* record */[
  /* age */33,
  /* name */"Igor",
  /* occupation */"Programmer"
];

var igorRecord = /* record */[
  /* person */igor,
  /* id */1
];

var sasha = /* record */[
  /* age */31,
  /* name */"Sasha",
  /* occupation */"Kinda Programmer"
];

var igorNextYear = /* record */[
  /* age */34,
  /* name */"Igor",
  /* occupation */"Programmer"
];

function sayName(param) {
  return "" + (String(param[/* name */1]) + (" is a " + (String(param[/* age */0]) + " years old")));
}

var greeting = sayName(sasha);

console.log(greeting);

exports.igor = igor;
exports.igorRecord = igorRecord;
exports.sasha = sasha;
exports.igorNextYear = igorNextYear;
exports.sayName = sayName;
exports.greeting = greeting;
/* greeting Not a pure module */
